In [ ]:
# https://www.kaggle.com/c/titanic/overview

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")

In [ ]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

### Preprocessing

In [ ]:
train.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# Droped colm
l1 = ['PassengerId', 'Cabin', 'Name', 'Ticket']

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [ ]:
train.drop(l1, axis = 1, inplace= True)
test.drop(l1, axis = 1, inplace = True)

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [ ]:
train.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
test.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [ ]:
# filling age missing values
train["Age"].fillna(train["Age"].median(), inplace = True, axis = 0)
test["Age"].fillna(train["Age"].median(), inplace = True, axis = 0)

In [ ]:
train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [ ]:
test.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [ ]:
train.shape, test.shape

((891, 8), (418, 7))

In [ ]:
train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
count_s = 0
count_c = 0
count_q = 0
for i in np.array(train['Embarked']):
    if i == 'S':
        count_s += 1
    elif i == 'C':
        count_c += 1
    elif i == 'Q' :
        count_q += 1

print(f"S --> {count_s}")
print(f"C --> {count_c}")
print(f"Q --> {count_q}")

S --> 644
C --> 168
Q --> 77


In [ ]:
list(train["Embarked"].mode())[0]

'S'

In [ ]:
emb = list(train["Embarked"].mode())[0]
train["Embarked"].fillna(emb, inplace = True, axis = 0)

In [ ]:
train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
test.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [ ]:
test["Fare"]

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...   
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [ ]:
Mean = test["Fare"].mean()
Median = test["Fare"].median()
# Mode = test["Fare"].mode()
print(f"mean --> {Mean}")
print(f"median --> {Median}")
# print(f"mode --> {Mode}")

mean --> 35.6271884892086
median --> 14.4542


In [ ]:
train.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
train["Fare"].median()

14.4542

In [ ]:
test['Fare'].fillna(train["Fare"].median(), axis = 0, inplace = True)

In [ ]:
train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
test.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
train.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
# Age train
train.loc[train["Age"] <= 16, 'Age'] = 0
train.loc[(train["Age"] > 16) & (train["Age"] <= 26), 'Age'] = 1
train.loc[(train["Age"] > 26) & (train["Age"] <= 36), 'Age'] = 2
train.loc[(train["Age"] > 36) & (train["Age"] <= 62), 'Age'] = 3
train.loc[train["Age"] > 62, 'Age'] = 4

In [ ]:
train.head()

Survived  Pclass     Sex  Age  SibSp  Parch     Fare Embarked
0         0       3    male  1.0      1      0   7.2500        S
1         1       1  female  3.0      1      0  71.2833        C
2         1       3  female  1.0      0      0   7.9250        S
3         1       1  female  2.0      1      0  53.1000        S
4         0       3    male  2.0      0      0   8.0500        S

In [ ]:
train["Age"].unique()

array([1., 3., 2., 0., 4.])

In [ ]:
# Age train
test.loc[test["Age"] <= 16, 'Age'] = 0
test.loc[(test["Age"] > 16) & (test["Age"] <= 26), 'Age'] = 1
test.loc[(test["Age"] > 26) & (test["Age"] <= 36), 'Age'] = 2
test.loc[(test["Age"] > 36) & (test["Age"] <= 62), 'Age'] = 3
test.loc[test["Age"] > 62, 'Age'] = 4

In [ ]:
test["Age"].unique()

array([2., 3., 1., 0., 4.])

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      418 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [ ]:
train.head()

Survived  Pclass     Sex  Age  SibSp  Parch     Fare Embarked
0         0       3    male  1.0      1      0   7.2500        S
1         1       1  female  3.0      1      0  71.2833        C
2         1       3  female  1.0      0      0   7.9250        S
3         1       1  female  2.0      1      0  53.1000        S
4         0       3    male  2.0      0      0   8.0500        S

In [ ]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
le_emb = LabelEncoder()

In [ ]:
# changing in train
train["Sex"] = le_sex.fit_transform(train["Sex"])
train["Embarked"] = le_emb.fit_transform(train.Embarked)

In [ ]:
# changing in test
test["Sex"] = le_sex.transform(test["Sex"])
test["Embarked"] = le_emb.transform(test.Embarked)

In [ ]:
train.head()

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0         0       3    1  1.0      1      0   7.2500         2
1         1       1    0  3.0      1      0  71.2833         0
2         1       3    0  1.0      0      0   7.9250         2
3         1       1    0  2.0      1      0  53.1000         2
4         0       3    1  2.0      0      0   8.0500         2

In [ ]:
test.head()

Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0       3    1  2.0      0      0   7.8292         1
1       3    0  3.0      1      0   7.0000         2
2       2    1  3.0      0      0   9.6875         1
3       3    1  2.0      0      0   8.6625         2
4       3    0  1.0      1      1  12.2875         2

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    int64  
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      418 non-null    float64
 6   Embarked  418 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 23.0 KB


In [ ]:
# changing to numpy array
X = train.iloc[:, 1: ].values
y = train.iloc[:, 0].values
test = test.values

In [ ]:
# spliting into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15)
X_train.shape, y_train.shape

((757, 7), (757,))

# SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
clf = SVC(C = 10)

In [ ]:
clf.fit(X_train, y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
clf.score(X_train, y_train)

0.7040951122853368

In [ ]:
clf.score(X_test, y_test)

0.7014925373134329

In [ ]:
y_pred = clf.predict(test)

In [ ]:
sub = pd.read_csv("/content/gender_submission.csv")
sub.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [ ]:
sub.shape, len(y_pred)

((418, 2), 418)

In [ ]:
sub.Survived = y_pred

In [ ]:
sub.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [ ]:
sub

In [ ]:
y_pred[:5]

array([0, 0, 0, 0, 0])

In [ ]:
sub.to_csv("ans.csv", index= None)

In [ ]:
!mv '/content/ans.csv' '/content/drive/My Drive/WE CBS'

# Bagging and Boosting

## Bagging --> Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators= 10, n_jobs= -1, max_depth= 5)

In [ ]:
clf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
clf1.score(X_train, y_train)

0.8428005284015853

In [ ]:
clf1.score(X_test, y_test)

0.8507462686567164

In [ ]:
sub.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [ ]:
y_pred = clf1.predict(test)

In [ ]:
sub['Survived'] = y_pred

In [ ]:
# sub['Survived'] = y_pred
sub.to_csv("ans_rf.csv", index= None)

In [ ]:
# sub['Survived'] = y_pred
# sub.to_csv("ans_rf.csv", index= None)
!mv '/content/ans_rf.csv' '/content/drive/My Drive/WE CBS'

## Boosting --> (Adaboost, XGboost)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
clf2 = AdaBoostClassifier(n_estimators= 50)

In [ ]:
clf2.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [ ]:
clf2.score(X_train, y_train)

0.8309114927344782

In [ ]:
clf2.score(X_test, y_test)

0.8208955223880597

In [ ]:
y_pred = clf2.predict(test)

In [ ]:
sub['Survived'] = y_pred
sub.to_csv("ans_ada.csv", index= None)
!mv '/content/ans_ada.csv' '/content/drive/My Drive/WE CBS'

In [ ]:
from xgboost import XGBClassifier

In [ ]:
clf3 = XGBClassifier(n_estimators= 10)

In [ ]:
clf3.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=10, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
clf3.score(X_train, y_train)

0.8124174372523117

In [ ]:
clf3.score(X_test, y_test)

0.7910447761194029

In [ ]:
y_pred = clf.predict(test)

In [ ]:
# y_pred = clf.predict(test)
sub['Survived'] = y_pred
sub.to_csv("ans_xg1.csv", index= None)
!mv '/content/ans_xg1.csv' '/content/drive/My Drive/WE CBS'

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cv_s = cross_val_score(clf3, X_train, y_train, cv = 10, n_jobs= -1)

In [ ]:
cv_s

array([0.76315789, 0.88157895, 0.76315789, 0.84210526, 0.76315789,
       0.84210526, 0.81578947, 0.77333333, 0.84      , 0.85333333])

In [ ]:
cv_s.mean()

0.8137719298245614

In [ ]:
# hyper parameter tunning

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param = {
    'n_estimators' : [10, 20, 50, 70, 100],
    'max_depth' : [3,4,5],
    'learning_rate' : [0.1, 0.3],
    'base_score' : [0.5, 0.7]
}

In [ ]:
grid_clf = GridSearchCV(clf3, param_grid= param, n_jobs = -1, cv = 10)

In [ ]:
grid_clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=10, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=-1,
             param_grid={'base_score': [0.5, 0.7], 'learning_rate': [0.1, 0.3],
                         'max_depth': [3, 4, 5],
                         'n_estimators': [10, 20, 

In [ ]:
grid_clf.best_params_

{'base_score': 0.7, 'learning_rate': 0.3, 'max_depth': 3, 'n_estimators': 70}

In [ ]:
grid_clf.best_score_

0.8361754385964912

In [ ]:
y_pred = clf.predict(test)
sub['Survived'] = y_pred
sub.to_csv("ans_xg_grid.csv", index= None)
!mv '/content/ans_xg_grid.csv' '/content/drive/My Drive/WE CBS'

In [ ]:
Ypred = grid_clf.predict(X_test)

In [ ]:
# confusion metrics
from sklearn.metrics import confusion_matrix
confusion_matrix(Ypred, y_test)

array([[70, 17],
       [10, 37]])

In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, Ypred))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        80
           1       0.79      0.69      0.73        54

    accuracy                           0.80       134
   macro avg       0.80      0.78      0.79       134
weighted avg       0.80      0.80      0.80       134

