# Numpy

In [0]:
import numpy as np

In [0]:
# l1 = list(range(100000000))

In [0]:
# %timeit sum(l1)

1 loop, best of 3: 528 ms per loop


In [0]:
# b = np.array(l1)

In [0]:
# type(b)

numpy.ndarray

In [0]:
# %timeit np.sum(b)

10 loops, best of 3: 94.2 ms per loop


In [0]:
# type(b[0])

numpy.int64

## Start

In [0]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [0]:
type(a)

numpy.ndarray

In [0]:
# Broadcasting
a = a + 15
a

array([16, 17, 18, 19, 20])

In [0]:
a = a- 5
a

array([11, 12, 13, 14, 15])

In [0]:
arr = np.array([1,1,1,1,1,1])

In [0]:
arr = arr*150
arr

array([150, 150, 150, 150, 150, 150])

In [0]:
a = a*2
a

array([22, 24, 26, 28, 30])

In [0]:
a = a/4
a

array([5.5, 6. , 6.5, 7. , 7.5])

In [0]:
b = np.array([1,2,3,4,5])

In [0]:
b

array([1, 2, 3, 4, 5])

In [0]:
b = b**2
b

array([ 1,  4,  9, 16, 25])

### Opreation

In [0]:
l1 = [1,2,3]
l2 = [2,3,4]

In [0]:
for i in range(len(l1)) :
    print(l1[i] + l2[i])

3
5
7


In [0]:
a = np.array(l1)
b = np.array(l2)

In [0]:
a+b

array([3, 5, 7])

In [0]:
print(a)
print(b)

[1 2 3]
[2 3 4]


In [0]:
a*b

array([ 2,  6, 12])

In [0]:
a**b

array([ 1,  8, 81])

## Functions

In [0]:
a = np.zeros((3,4), dtype= 'int')

In [0]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
b = np.zeros((3,3,3))
b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [0]:
b.shape

(3, 3, 3)

In [0]:
a = np.ones((4,3))

In [0]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
b = np.eye(5)

In [0]:
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
b.shape

(5, 5)

In [0]:
a = np.array(["usa", "uk", "spain"])

In [0]:
a

array(['usa', 'uk', 'spain'], dtype='<U5')

In [0]:
a.shape

(3,)

In [0]:
np.ones((3,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [0]:
np.zeros((3,5))+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

# Random

In [0]:
np.random.randint(1, 10)

8

In [0]:
for i in range(10) :
    print(np.random.randint(1, 10))

5
4
1
6
6
7
3
2
9
5


In [0]:
a = np.random.randint(1, 10, (4,3))
a

array([[1, 1, 3],
       [9, 8, 7],
       [7, 4, 8],
       [8, 9, 5]])

In [0]:
a.shape

(4, 3)

## More Fuction

In [0]:
a = np.array([[1,3], [4,7]])
a

array([[1, 3],
       [4, 7]])

In [0]:
a.min()

1

In [0]:
a.max()

7

In [0]:
print(a)
a.mean(axis = 1)

[[1 3]
 [4 7]]


array([2. , 5.5])

In [0]:
a.std(axis= 0)

array([1.5, 2. ])

In [0]:
a.std(axis=1)

array([1. , 1.5])

In [0]:
a.shape

(2, 2)

In [0]:
np.random.seed(12)
np.random.randint(1, 10)

7

In [0]:
a = np.array([1,2,3])
b= np.array([8,7,6])

In [0]:
a, b

(array([1, 2, 3]), array([8, 7, 6]))

In [0]:
np.stack((b,a), axis = 0)

array([[8, 7, 6],
       [1, 2, 3]])

In [0]:
import numpy as np

In [0]:
n = [int(i) for i in input().strip().split()][:2]
print("n --> ",end = " ")
print(n)

a = [] # empty list
for i in range(n[0]): # no of rows
    temp = input().strip().split()
    temp = [int(i) for i in temp][:n[1]]
    print("temp --> ", end= " ")
    print(temp)
    print(type(temp))
    a.append(temp)

print("a --> ",end = " ")
print(a)

2 2
n -->  [2, 2]
2 3 4 5
temp -->  [2, 3]
<class 'list'>
 4 5 6
temp -->  [4, 5]
<class 'list'>
a -->  [[2, 3], [4, 5]]
